{
  #your IP and port with which to provision your APIs
  'ip': '172.21.0.1',
  'port': '7777',

  #ip and port where elasticsearch runs on your system
  'elasticsearch_ip': '172.21.0.1',
  'elasticsearch_port': '9200',

  #API ENDPOINTS
  'stored_intents_url': 'http://172.21.0.1:7777/stored_intents',
  'intents_url': 'http://172.21.0.1:7777/intents',
  'stored_qos_intents_url': 'http://172.21.0.1:7777/stored_qos_intents',
  'qos_intents_url': 'http://172.21.0.1:7777/qos_intents',

  #PROVISIONED BY THE IBI
  #eg API endpoint for sending intents: "http://172.21.0.1:7777/intents"
  #the API for sending intents is where the DTE sends intents
  'to_enter_intents': '/intents',
  #the receive_whatif API is the API for receiving what-if answers from the SAN
  'to_receive_whatif': '/whatif_receives',
  #the stored_intents API is for viewing and deleting existing intents
  'to_view_or_delete_intents': '/stored_intents',
  #the API for sending intents is where the DTE sends intents
  'to_enter_qos_intents': '/qos_intents',
  #the stored_intents API is for viewing and deleting existing intents
  'to_view_or_delete_qos_intents': '/stored_qos_intents',

  #PROVISIONED BY OTHER MODULES
  #the API for sending workflow is the API for sending workflows to RTR
  'to_send_workflow': '/workflows',
  'rtr_api_url': 'http://0.0.0.0:8000',
  'rtr_username': 'user3',
  'rtr_password': 'user3',
  'rtr_email': 'user3@gmail.com',
  'to_connect_to_rtr': 'true',

  #the send_whatif API is the API for sending what-if questions to the SAN
  'to_send_whatif': '/whatif_sends',
  'san_api_url': 'http://172.21.0.1:7777/whatif_sends',


  #to clear existing intent store if you want, otherwise, set it as 'false'
  'clear_intent_store': 'true',

  #directories and files
  'templates_directory': 'templates',
  'static_directory': 'static',
  'policy_store_file': 'policy_store.csv',

  #attack types, mitigation actions and hosts
  'ddos_ntp': {
    'monlist_disable': 'ntp_s',
    'ntp_service_switch_off': 'ntp_s',
    'absorb_traffic': 'r2',
    'server_handover': 'ntp_s',
    'firewall_spoofing_detection': 'r2',
    'upgrade_software': 'ntp_s',
    'investigations_report': 'request_to_network_admin'
  },
  'ddos_dns': {
    'dns_service_disable': 'dns_s',
    'absorb_traffic': 'r2',
    'server_handover': 'dns_s',
    'firewall_spoofing_detection': 'r2',
    'rate_limiting': 'dns_s',
    'investigations_report': 'request_to_network_admin'
  },
  'ddos_pfcp': {
    'sba_function_disable': 'orchestrator',
    'new_ns_slice_creation': 'oss',
    'rate_limiting': 'smf',
    'investigations_report': 'request_to_network_admin'
  },

  #examples of operator's qos requirements definition
  'qos_requirements': [{
    'intent_type': 'qos_ntp',
    'name': 'reliability',
    'value': 0.9,
    'host': ['192.164.56.20', '192.164.58.34']
  },
  {
    'intent_type': 'qos_dns',
    'name': 'latency',
    'value': 0.2,
    'host': [ '192.164.56.20', '192.164.58.34' ]
  },
  {
    'intent_type': 'qos_pfcp',
    'name': 'bandwidth',
    'value': 5000,
    'host': [ '192.164.56.20', '192.164.58.34' ]
  }],

  #TOPOLOGY
  'hosts': {
    'dns-c1': '',
    'dns-c2': '',
    'dns-c3': '',
    'dns-c4': '',
    'dns-c5': '',
    'dns-c6': '',
    'dns-c7': '',
    'dns-c8': '',
    'dns-c9': '',
    'dns-c10': '',
    'gnb': '',
    'ceos1': '',
    'ceos2': '',
    'upf': '',
    'dns-s': '',
    'gateway': '',
    'ausf': '',
    'amf': '',
    'smf': '',
    'udm': '',
    'nssf': '',
    'udr': '',
    'nrf': '',
    'pcf': '',
  },

  'links': [
    {
      a_node: dns-c1,
      a_int: eth1,
      z_node: gnb,
      z_int: eth1
    },
    {
      a_node: dns-c2,
      a_int: eth1,
      z_node: gnb,
      z_int: eth2
    },
    {
      a_node: dns-c3,
      a_int: eth1,
      z_node: gnb,
      z_int: eth3
    },
    {
      a_node: dns-c4,
      a_int: eth1,
      z_node: gnb,
      z_int: eth4
    },
    {
      a_node: dns-c5,
      a_int: eth1,
      z_node: gnb,
      z_int: eth5
    },
    {
      a_node: dns-c6,
      a_int: eth1,
      z_node: gnb,
      z_int: eth6
    },
    {
      a_node: dns-c7,
      a_int: eth1,
      z_node: gnb,
      z_int: eth7
    },
    {
      a_node: dns-c8,
      a_int: eth1,
      z_node: gnb,
      z_int: eth8
    },
    {
      a_node: dns-c9,
      a_int: eth1,
      z_node: gnb,
      z_int: eth9
    },
    {
      a_node: dns-c10,
      a_int: eth1,
      z_node: gnb,
      z_int: eth10
    },
    {
      a_node: ceos1,
      a_int: eth1,
      z_node: gnb,
      z_int: eth11
    },
    {
      a_node: ceos1,
      a_int: eth2,
      z_node: ceos2,
      z_int: eth1
    },
    {
      a_node: ceos1,
      a_int: eth3,
      z_node: upf,
      z_int: eth1
    },
    {
      a_node: ceos2,
      a_int: eth2,
      z_node: dns-s,
      z_int: eth1
    },
    {
      a_node: ceos2,
      a_int: eth3,
      z_node: gateway,
      z_int: eth1
    },
    {
      a_node: ceos1,
      a_int: eth4,
      z_node: ausf,
      z_int: eth1
    },
    {
      a_node: ceos1,
      a_int: eth4,
      z_node: amf,
      z_int: eth1
    },
    {
      a_node: ceos1,
      a_int: eth4,
      z_node: smf,
      z_int: eth1
    },
    {
      a_node: ceos1,
      a_int: eth4,
      z_node: udm,
      z_int: eth1
    },
    {
      a_node: ceos1,
      a_int: eth4,
      z_node: nssf,
      z_int: eth1
    },
    {
      a_node: ceos1,
      a_int: eth4,
      z_node: udr,
      z_int: eth1
    },
    {
      a_node: ceos1,
      a_int: eth4,
      z_node: nrf,
      z_int: eth1
    },
    {
      a_node: ceos1,
      a_int: eth4,
      z_node: pcf,
      z_int: eth1
    }
  ],










}
